---
- name: add repository key
  command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9

- lineinfile: line="deb http://get.docker.io/ubuntu docker main" dest=/etc/apt/sources.list.d/docker.list mode=644 create=yes

- name: Install aufs
  apt: pkg=linux-image-extra-3.13.0-48-generic update_cache=yes

- name: install docker package
  apt: name=lxc-docker state=present

- template: src=docker.j2 dest=/etc/default/docker

- service: name="docker" state="restarted"
